Inspectra.WebUI/Models/CamerasListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Inspectra.Domain.Entities;

namespace Inspectra.WebUI.Models
{
    public class CamerasListViewModel
    {
        public IEnumerable<Camera> Cameras { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentLocation { get; set; }
    }
}

Inspectra.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Inspectra.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Inspectra.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Inspectra.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

Inspectra.WebUI/Controllers/AccountController.cs
using Inspectra.WebUI.Infrastructure.Abstract;
using Inspectra.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspectra.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }
        public ViewResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

    }
}

Inspectra.WebUI/Controllers/AdminController.cs
using Inspectra.Domain.Abstract;
using Inspectra.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspectra.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        private ICameraRepository repository;

        public AdminController(ICameraRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Cameras);
        }


        public ViewResult Edit(int cameraId)
        {
            Camera camera = repository.Cameras
              .FirstOrDefault(p => p.CameraID == cameraId);
            return View(camera);
        }


        //[HttpPost]
        //public ActionResult Edit(Camera camera)
        //{
        //    if (ModelState.IsValid)
        //    {          
        //        repository.SaveCamera(camera);
        //        TempData["message"] = string.Format("{0} has been saved", camera.Name);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        // there is something wrong with the data values
        //        return View(camera);
        //    }
        //}

        [HttpPost]
        public ActionResult Edit(Camera camera, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    camera.ImageMimeType = image.ContentType;
                    camera.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(camera.ImageData, 0, image.ContentLength);
                }
                repository.SaveCamera(camera);
                TempData["message"] = string.Format("{0} has been saved", camera.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(camera);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Camera());
        }


        [HttpPost]
        public ActionResult Delete(int cameraId)
        {
            Camera deletedCamera = repository.DeleteCamera(cameraId);
            if (deletedCamera != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedCamera.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

Inspectra.WebUI/Controllers/CameraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inspectra.Domain.Abstract;
using Inspectra.Domain.Entities;
using Inspectra.WebUI.Models;

namespace Inspectra.WebUI.Controllers
{
    public class CameraController : Controller
    {
        //
        // GET: /Camera/
        private ICameraRepository repository;
        public int PageSize = 2;
        public CameraController(ICameraRepository cameraRepository)
        {
            this.repository = cameraRepository;
        }

        //public ViewResult List()
        //{
        //    return View(repository.Cameras);
        //}


        public ViewResult List(string location, int page = 1)
        {
            //return View(repository.Cameras
            //  .OrderBy(p => p.CameraID)
            //  .Skip((page - 1) * PageSize)
            //  .Take(PageSize));

            CamerasListViewModel model = new CamerasListViewModel
            {
                Cameras = repository.Cameras
                .Where(p => location == null || p.Location == location)
                  .OrderBy(p => p.CameraID)
                  .Skip((page - 1) * PageSize)
                  .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = location == null ?
                        repository.Cameras.Count() :
                        repository.Cameras.Where(e => e.Location == location).Count()
                },

            CurrentLocation = location
            };

            return View(model);
        }

        public FileContentResult GetImage(int cameraId)
        {
            Camera prod = repository.Cameras.FirstOrDefault(p => p.CameraID == cameraId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

    }
}

Inspectra.WebUI/Controllers/NavController.cs
using Inspectra.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspectra.WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/

        private ICameraRepository repository;

        public NavController(ICameraRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string location = null)
        {
            ViewBag.SelectedLocation = location;
            IEnumerable<string> locations = repository.Cameras
              .Select(x => x.Location)
              .Distinct()
              .OrderBy(x => x);
            return PartialView(locations);

        }
    }
}

Inspectra.WebUI/Views/Admin/Edit.cshtml
@model Inspectra.Domain.Entities.Camera

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>
@using (Html.BeginForm("Edit", "Admin",
  FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.EditorForModel()
    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:None
    }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "Camera", new { Model.CameraID })" />
        }
        <div>
            Upload new image:
            <input type="file" name="Image" />
        </div>
    </div>
    <input type="submit" value="Save" />
    @Html.ActionLink("Cancel and return to List", "Index")
}

Inspectra.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Inspectra.Domain.Entities.Camera>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Cameras</h1>
<table class="Grid">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CameraID</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { item.CameraID })</td>
            <td>@item.Address.ToString()</td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("CameraID", item.CameraID)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>
<p>@Html.ActionLink("Add a new camera", "Create")</p>

Inspectra.WebUI/Views/Camera/List.cshtml
@model Inspectra.WebUI.Models.CamerasListViewModel

@{
    ViewBag.Title = "Cameras";
}

@foreach (var p in Model.Cameras)
{
    Html.RenderPartial("CameraSummary", p);
}

<div class="pager">
   @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
    new { page = x, location = Model.CurrentLocation }))
</div>

Inspectra.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Camera")

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Camera",
        action = "List",
        location = link,
        page = 1
    },
        new
        {
            @class = link == ViewBag.SelectedLocation ? "selected" : null
        }
    
    )
}

Inspectra.WebUI/Views/Shared/CameraSummary.cshtml
@model Inspectra.Domain.Entities.Camera

<div class="item">
    @if (Model.ImageData != null)
    {
        <div style="float: left; margin-right: 20px">
            <img width="75" height="75" src="@Url.Action("GetImage", "Camera", new { Model.CameraID })" />
        </div>
    }
    <h3>@Model.Name</h3>
    @Model.Description
    <h4>@Model.Address.ToString()</h4>
</div>

Inspectra.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

Inspectra.WebUI/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <div class="title">INSPECTRA</div>
    </div>
    <div id="locations">     
        @{ Html.RenderAction("Menu", "Nav"); }  
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>